apps/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',
         views.register,
         name='register'
         ),

    path('profile/',
         views.profile,
         name='profile'
         ),

    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),

    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'
         ),

    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='users/email_template.html'
        ),
        name='password_reset'
    ),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path(
        'password_reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete')
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeTemplateView.as_view(), name="home_url"),
    path('users/', include('users.urls', namespace='users')),

    path('detectobj/', include("detectobj.urls", namespace="detectobj")),
    path('modelmanager/', include("modelmanager.urls", namespace="modelmanager")),
    # path('croppedimages/', include("croppedimages.urls", namespace="croppedimages")),
    path('images/', include("images.urls", namespace="images")),
    # path('test/', include("test_app.urls", namespace="test_app")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

apps/users/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from PIL import Image


class Organization(models.TextChoices):
    A = 'A', _("Male")
    B = 'B', _("Female")


class CustomUser(AbstractUser):
    orig_name = models.CharField(
        choices=Organization.choices, max_length=2)
    age = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=21, null=True, blank=True)


class Profile(models.Model):
    user = models.OneToOneField("users.CustomUser", on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from .models import CustomUser as User

GENDER_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female')
]

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    gender = forms.ChoiceField(choices=GENDER_CHOICES)

    class Meta:
        model = User
        fields = ['username', 'email', 'gender', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import CustomUser as User


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            user.is_active = True
            user.save()
            messages.success(
                request, f'Your account with {username} has been created! You are now able to log in')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


class RegistrationUnderApproval(TemplateView):
    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

apps/users/templates/users/email_template.html
{% autoescape off %}
You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

Your username, in case you've forgotten: {{ user.username }}
Thanks for using our site!

The {{ site_name }} team.

{% endautoescape %}

apps/users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Log In
{% endblock title %}

{% block content %}
<section class="h-100 gradient-form" style="background-color: white;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">

            <div class="col-xl-10">
                <div class="card rounded-3 text-black">
                    <div class="row g-0">
                        <div class="col-lg-6">
                            <div class="card-body p-md-5 mx-md-4">
                                <div class="text-center">
                                    <h4 class="mt-1 mb-5 pb-1">Welcome to DetectHub</h4>
                                </div>
                                <h2 class="card-title text-center mb-4">Log In</h2>
                                <form method="POST" action="">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <div class="text-center mt-4">
                                        <button class="btn btn-outline-info btn-block" type="submit">
                                            <span class="btn-text">Login</span>
                                        </button>
                                    </div>
                                </form>
                                <hr class="bg-light">
                                <div class="text-center">
                                    <small class="text-muted">
                                        <a href="{% url 'accounts:password_reset' %}" class="text-dark">Forgot Password?</a>
                                    </small>
                                </div>
                                <div class="text-center mt-3">
                                    <small class="text-muted">Need An Account? <a href="{% url 'accounts:register' %}" class="text-dark">Sign Up Now</a></small>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                            <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                <h4 class="mb-4">We are more than just a Website</h4>
                                <p class="small mb-0">DetectHub is a community and sharing platform in the fields of computer vision, artificial intelligence, machine learning, and object detection.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<style>
    body {
        background-color: white;
    }

    .gradient-custom-2 {
        background: #000; /* Siyah arka plan */
        color: white; /* Yazı rengi beyaz */
        border-top-right-radius: .3rem;
        border-bottom-right-radius: .3rem;
    }

    .navbar {
        padding-top: 25px;
        padding-bottom: 25px;
    }

    .gradient-form {
        margin-top: 80px;
    }

    .btn-outline-info {
        color: black;
        border-color: black;
    }
    .btn-outline-info:hover {
        color: white;
        background-color: black;
        border-color: black;
    }
    .btn-text {
        display: block;
    }
</style>
{% endblock content %}

apps/users/templates/users/logout.html
{% extends "base.html" %}

{% block title %}
    Log Out
{% endblock title %}

{% block content %}
<section class="h-100 gradient-form" style="background-color: white;">
    <div class="container py-5 h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-md-6">
                <div class="card border-dark shadow-lg">
                    <div class="card-body p-5">
                        <h2 class="card-title text-center mb-4">You have been logged out</h2>
                        <div class="text-center mt-4">
                            <a href="{% url 'users:login' %}" class="btn btn-outline-info">Log In Again</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block extra_head %}
<style>
    body {
        background-color: white;
    }

    .gradient-form {
        margin-top: 80px;
    }

    .btn-outline-info {
        color: black;
        border-color: black;
    }
    .btn-outline-info:hover {
        color: white;
        background-color: black;
        border-color: black;
    }

    .navbar {
        padding-top: 25px;
        padding-bottom: 25px;
    }
</style>
{% endblock extra_head %}

apps/users/templates/users/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Reset Password
{% endblock title %}

{% block content %}
<section class="h-100 gradient-form" style="background-color: white;">
    <div class="container mt-5">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card border-dark shadow-lg">
                    <div class="card-body p-5">
                        <h2 class="card-title text-center mb-4">Reset Password</h2>
                        <form method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <div class="text-center mt-4">
                                <button class="btn btn-outline-info btn-block" type="submit">
                                    <span class="btn-text">Request Password Reset</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block extra_head %}
<style>
    body {
        background-color: white;
    }

    .gradient-form {
        margin-top: 80px;
    }

    .card {
        border: 1px solid #000;
    }

    .btn-outline-info {
        color: black;
        border-color: black;
    }
    .btn-outline-info:hover {
        color: white;
        background-color: black;
        border-color: black;
    }

    .navbar {
        padding-top: 25px;
        padding-bottom: 25px;
    }
</style>
{% endblock extra_head %}

apps/users/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block title %}
Password Reset Complete
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}
{% block content %}
<div class="col-sm-8">
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'users:login' %}" class="btn btn-primary" role=button> Sign In Here</a>
</div>
{% endblock content %}

apps/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Password Reset Confirm
{% endblock title %}
{% url 'account:password_reset_confirm' uidb64=uid token=token %}
{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}
{% block content %}
<div class="col-sm-8">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

apps/users/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}
Password Reset Done
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-sm-8">
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
</div>
{% endblock content %}

apps/users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}
  {{ request.user.username|capfirst }}'s Profile
{% endblock title %}

{% block leftbar %}
<div class="col-sm-3">
    
</div>
{% endblock leftbar %}

{% block content %}
    <div class="col-sm-7">
      <div class="content-section">
        <div class="media">
          <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
          <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
          </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
      </div>
    </div>
{% endblock content %}

apps/users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock title %}

{% block content %}
    <section class="h-100 gradient-form" style="background-color: white;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 mx-md-4">
                                    <div class="text-center">
                                        <h4 class="mt-1 mb-5 pb-1">Welcome to DetectHub</h4>
                                    </div>
                                    <h2 class="card-title text-center mb-4">Register</h2>
                                    <form method="POST">
                                        {% csrf_token %}
                                        {{ form.username|as_crispy_field }}
                                        {{ form.email|as_crispy_field }}
                                        {{ form.gender|as_crispy_field }}
                                        {{ form.password1|as_crispy_field }}
                                        {{ form.password2|as_crispy_field }}
                                        <div class="text-center mt-4">
                                            <button class="btn btn-outline-info btn-block" type="submit">
                                                <span class="btn-text">Sign Up</span>
                                            </button>
                                        </div>
                                    </form>
                                    <hr class="bg-light">
                                    <div class="border-top pt-3">
                                        <small class="text-muted">
                                            Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
                                        </small>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center gradient-custom-2 text-white">
                                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                    <h4 class="mb-4">Be Part of a Thriving AI Community</h4>
                                    <p class="small mb-0">By joining our community, you gain access to a wealth of knowledge and resources in the fields of computer vision, artificial intelligence, machine learning, and object detection.</p>
                                    <p></p>
                                    <p class="small mb-0">As a member, you can:</p>
                                    <p></p>
                                    <ul class="small mb-0">
                                        <li>Collaborate on projects and share your own work.</li>
                                        <li>Get feedback and support from experts and peers.</li>
                                    </ul>
                                    <p></p>
                                    <p class="small mb-0">We look forward to seeing what you create and contribute to our vibrant community!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block extra_head %}
<style>
    body {
        background-color: white;
    }

    .gradient-custom-2 {
        background: #000;
        border-top-right-radius: .3rem;
        border-bottom-right-radius: .3rem;
    }

    .navbar {
        padding-top: 25px;
        padding-bottom: 25px;
    }

    .gradient-form {
        margin-top: 10px;
    }

    .btn-outline-info {
        color: black;
        border-color: black;
    }
    .btn-outline-info:hover {
        color: white;
        background-color: black;
        border-color: black;
    }
    .btn-text {
        display: block;
    }
    .navbar-nav {
        flex-direction: row;
    }

    .nav-link {
        padding-right: 15px !important;
        padding-left: 15px !important;
    }

    .navbar .container {
        display: flex;
        justify-content: center;
    }

    .navbar-collapse {
        justify-content: center;
    }
</style>
{% endblock extra_head %}

apps/users/templates/users/registration_success.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block on_page_css %}
{% endblock on_page_css %}

{% block title %}
Registration Success
{% endblock title %}

{% block leftbar %}
<div class='col-sm-3'>
</div>
{% endblock leftbar %}

{% block content %}
<div class='col-sm-9 mt-2' id='main-div'>
    <div class="alert alert-primary" role="alert">
        Dear User {{ self.request.user }}! Your registration is success.
    </div>
</div>
{% endblock content %}

{% block model %}
{% endblock model %}

{% block on_page_script %}
{% endblock on_page_script %}

apps/users/templates/users/registration_under_approval.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block on_page_css %}
{% endblock on_page_css %}

{% block title %}
Registration Under Approval
{% endblock title %}

{% block leftbar %}
<div class='col-sm-3'>
</div>
{% endblock leftbar %}

{% block content %}
<div class='col-sm-9 mt-2' id='main-div'>
    <div class="alert alert-primary" role="alert">
        Dear User {{ self.request.user }}! Your registration is under approval.
    </div>
</div>
{% endblock content %}

{% block model %}
{% endblock model %}

{% block on_page_script %}
{% endblock on_page_script %}